-- Remove the table if it exists
DROP TABLE IF EXISTS products;

-- Create the table
CREATE TABLE products (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    subTitle TEXT,
    rating INTEGER,
    imgSrc TEXT,
    listProcessor TEXT,
    listMemory TEXT,
    listStrength TEXT,
    strikeThrough INTEGER,
    price INTEGER
);

-- Insert data into the table
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (1, '14" FHD-Chromebook med IPS & Intel®N4020', 'Acer Chromebook CB314 (NX.AUDED.00E)', 15, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/acer-chromebook-cb314-nx-auded-00e(1028065)_639561_9_Normal_Large.jpg', 'Intel Pentium N4020-processor', '64 GB eMMC & 4 GB RAM', 'Upp till 12,5 timmar batteritid', 2790, 2490);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (2, '14" FHD-laptop med mycket prestanda för pengarna', 'Ångström (M1HOME)', 31, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/angstrom-angstrom-m1home(1028915)_555420_5_Normal_Large.jpg', 'Intel® Pentium™ Silver N5030', '64 GB SSD & 4 GB RAM', '14,1" Full HD-skärm', NULL, 2899);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (3, 'Lätt 14" Chromebook med 128 GB lagring & 15 h batteritid', 'Acer Chromebook 314 (NX.AWFED.009)', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/acer-chromebook-314-nx-awfed-009(1032684)_623915_1_Normal_Large.jpg', 'MediaTek MT8183 OctaCore-processor', '128 GB eMMC-lagring & 8 GB RAM', 'Upp till 15 timmars batteritid', 3290, 2690);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (4, 'Tunn och enkel 14" Chromebook med lång batteritid', 'Acer Chromebook 314 (NX.AWFED.00Q)', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/acer-chromebook-314-nx-awfed-00q(1032683)_638882_5_Normal_Large.jpg', 'MediaTek MT8183 OctaCore-processor', '32 GB eMMC & 4 GB RAM', 'Upp till 15 timmar batteritid', 3299, 2790);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (5, '14" laptop med 10:e Gen. i3 processor & 8 h batteritid', 'Medion E14409', 16, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/medion-e14409(1028245)_547834_1_Normal_Large.jpg', 'Intel Core i3 10:e gen. processor', '128 GB SSD & 4 GB RAM', 'Upp till 8 timmar batteritid', 3590, 2990);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (6, '14" Chromebook med lång batteritid & flexibel design', 'HP Chromebook Cx14a-ca0003 H/C4120/4/64/M/CH', 4, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/hp-chromebook-cx14a-ca0003-hc4120464mch(1028611)_573071_3_Normal_Large.jpg', 'Intel® Celeron® N4120-processor', '64 GB eMMC & 4 GB RAM', 'Upp till 13 timmar batteritid', NULL, 3499);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (7, '14" Chromebook för arbete och underhållning överallt', 'Acer Chromebook 314 (NX.KB4ED.00M)', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/acer-chromebook-314-nx-kb4ed-00m(1032808)_646769_7_Normal_Large.jpg', 'Intel® Celeron® N4500 processor', '64 GB lagring & 8 GB RAM', '14" Full HD-skärm', NULL, 3990);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (8, '17,3" laptop med HD-webbkamera & sekretesskydd', 'Lenovo IdeaPad 3 (82H900MWMX)', 4, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-17-18-tum/lenovo-ideapad-3-82h900mwmx(1030086)_595297_3_Normal_Large.jpg', 'Intel® Celeron® 6305 processor', '128 GB SSD & 4 GB RAM', '17,3" HD+ skärm (1600 x 900)', NULL, 4790);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (9, '14" Chromebook med Celeron®N4500-processor', 'Acer Chromebook Spin 314', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/acer-chromebook-spin-314(1032809)_646608_2_Normal_Large.jpg', 'Intel® Celeron® N4500-processor', '128 GB eMMC & 8 GB RAM', 'Upp till 10 timmars batteritid', NULL, 4990);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (10, 'Lätt 14" Chromebook med upp till 15 timmars batteritid', 'Acer Chromebook 314 (NX.AWFED.00G)', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/chromebook/acer-acer-chromebook-314-nx-awfed-00g(1027006)_538202_1_Normal_Large.jpg', 'MediaTek MT8183 processor', '64 GB SSD & 4 GB RAM', 'Upp till 15 timmars batteritid', NULL, 3490);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (11, '15,6" Chromebook för enkel användning på språng', 'Lenovo IdeaPad 3 Chrome', 3, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/lenovo-ideapad-3-chrome(1032867)_643850_1_Normal_Large.jpg', 'Intel® Celeron® N4500 processor', '128 GB lagring & 8 GB RAM', 'Snabb laddning via USB-C', NULL, 3490);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (12, '14" laptop med lång batteritid & 128 GB SSD', 'Lenovo IdeaPad 1', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/lenovo-ideapad-1(1032865)_641040_1_Normal_Large.jpg', 'Intel® Celeron® N4120-processor', '128 GB eMMC & 4 GB RAM', 'Upp till 11 timmar batteritid', NULL, 2990);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (13, '15,6" laptop med AMD processor & snabbladdning', 'HP Laptop 15-fc0017no', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/hp-laptop-15-fc0017no(1033455)_644308_1_Normal_Large.jpg', 'AMD Athlon™ Gold 7220U processor', '256 GB SSD & 8 GB DDR5 RAM', 'Ca. 10 tim & 30 min batteritid', NULL, 4990);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (14, 'Refurbished 14" arbetsdator med 256 GB SSD & 16 GB RAM', 'Lenovo ThinkPad T480s (Refurbished) A-grade', 1, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/lenovo-lenovo-thinkpad-t480s-refurbished-a-grade(1032944)_641917_1_Normal_Large.jpg', 'Intel Core i5-8350U processor', '256 GB SSD & 16 GB RAM', 'Gradering A = Utmärkt skick', NULL, 3990);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (15, '14" Chromebook med 13,5 h batteritid & 8 GB RAM', 'Lenovo IdeaPad 3 Chromebook', 4, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/lenovo-ideapad-3-chromebook(1031221)_622675_1_Normal_Large.jpg', 'MediaTek Kompanio 520-processor', '128 GB eMMC & 8 GB RAM', 'Upp till 13,5 timmar batteritid', NULL, 4490);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (16, '15,6" laptop med Intel processor & 128 GB eMMC', 'ASUS Laptop E510', 1, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/asus-asus-laptop-e510(1032988)_630134_2_Normal_Large.jpg', 'Intel® Celeron® N4500 processor', '128 GB eMMC & 4 GB RAM', 'Fläktlös design', NULL, 3499);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (17, 'Lätt & smidig 15,6" laptop med 128 GB lagring', 'ASUS Laptop E510 (L510KA-EJ738W)', 3, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/asus-asus-laptop-e510-l510ka-ej738w(1032990)_644682_3_Normal_Large.jpg', 'Intel® Celeron® N4500 processor', '128 GB eMMC & 8 GB RAM', 'Väjer endast 1,57 kg', NULL, 4499);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (18, '14" Chromebook med lång batteritid & snabbladdning', 'HP HP Chromebook 14a 14a-na0212no', 1, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/hp-hp-chromebook-14a-14a-na0212no(1031032)_619366_1_Normal_Large.jpg', 'Intel® Celeron® N4120-processor', '128 GB eMMC & 8 GB RAM', 'Upp till 12,5 timmar batteritid', NULL, 4990);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (19, 'Refurbished 14" laptop med i5 processor & 256 GB SSD', 'Dell Latitude 7490 (Refurbished) A-grade', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/dell-latitude-7490-refurbished-a-grade(1033404)_641933_1_Normal_Large.jpg', 'Intel® Core™ i5-8350U processor', '256 GB SSD & 8 GB RAM', 'Gradering A = Utmärkt skick', NULL, 3990);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (20, '14" FHD-laptop med mycket prestanda för pengarna', 'Ångström (M1HOME)', 31, 'https://www.netonnet.se/GetFile/ProductImagePrimary/outlet/dator/angstrom-x-m1home(X1028915)_555420_5_Normal_Large.jpg', 'Intel® Pentium™ Silver N5030', '64 GB SSD & 4 GB RAM', '14,1" Full HD-skärm', NULL, 2490);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (21, '14" laptop med 10:e Gen. i3 processor & 8 h batteritid', 'Medion E14409', 16, 'https://www.netonnet.se/GetFile/ProductImagePrimary/outlet/dator/medion-x-e14409(X1028245)_547834_1_Normal_Large.jpg', 'Intel Core i3 10:e gen. processor', '128 GB SSD & 4 GB RAM', 'Upp till 8 timmar batteritid', NULL, 2490);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (22, '14" laptop med 10 timmar batteritid & snabbladdning', 'Lenovo Ideapad 1 (82R00063MX)', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/outlet/dator/fyndvaror-laptop/laptop-14-16-tum/lenovo-x-ideapad-1-82r00063mx(X1028436)_572522_3_Normal_Large.jpg', 'AMD 3000 Series 3020E processor', '64 GB eMMC & 4 GB RAM', 'Upp till 10 timmar batteritid', NULL, 3190);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (23, '17,3" laptop med HD-webbkamera & sekretesskydd', 'Lenovo IdeaPad 3 (82H900MWMX)', 4, 'https://www.netonnet.se/GetFile/ProductImagePrimary/outlet/dator/lenovo-x-ideapad-3-82h900mwmx(X1030086)_595297_3_Normal_Large.jpg', 'Intel® Celeron® 6305 processor', '128 GB SSD & 4 GB RAM', '17,3" HD+ skärm (1600 x 900)', NULL, 4090);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (24, '14" laptop med lång batteritid & 128 GB SSD', 'Lenovo IdeaPad 1', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/outlet/dator/lenovo-x-ideapad-1(X1032865)_641040_1_Normal_Large.jpg', 'Intel® Celeron® N4120-processor', '128 GB eMMC & 4 GB RAM', 'Upp till 11 timmar batteritid', NULL, 2490);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (25, 'MacBook Air. Nu med Apple M1-chippet.', 'Apple MacBook Air 256GB M1 chip with 8-core CPU and 7-core GPU ', -113, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/apple-macbook-air-256gb-m1-chip-with-8-core-cpu-and-7-core-gpu-space-grey(1015638)_405111_5_Normal_Large.jpg', 'Apple M1-chip med Ã¥ttakÃ¤rnig processor', '8 GB RAM + 256 GB SSD', '16-kÃ¤rnig Neural Engine', NULL, 9989);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (26, 'Snabb 17,3" laptop med 512 GB SSD & WiFi 6', 'Acer Aspire 3 17', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-17-18-tum/acer-aspire-3-17(1033667)_663226_7_Normal_Large.jpg', 'Intel N-series N100 processor', '512 GB SSD & 8 GB DDR5 RAM', 'WiFi 6 och Bluetooth', NULL, 6490);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (27, 'Smidig 15,6" laptop med Intel processor & 512 GB SSD', 'Acer Aspire 3', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/acer-aspire-3(1033663)_663058_1_Normal_Large.jpg', 'IntelÂ® CeleronÂ® N4500 processor', '512 GB SSD & 8 GB RAM', 'Slimmad design', NULL, 5490);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (28, '14" Chromebook Plus med Intel Core i3 processor', 'Acer Chromebook Plus 514', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/chromebook/acer-chromebook-plus-514(1033664)_663939_1_Normal_Large.jpg', 'IntelÂ® Coreâ„¢ i3 N305 processor', '256 GB SSD & 8 GB LPDDR5 RAM', '14" Full HD-skÃ¤rm (1920 x 1080)', NULL, 6290);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (29, '15,6" laptop med Ryzen 7 processor & 32 GB RAM-minne', 'Acer Aspire 3 15 (NX.KSJED.003)', -18, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/acer-aspire-3-15-nx-ksjed-003(1031132)_615203_1_Normal_Large.jpg', 'AMD Ryzenâ„¢ 7 5700U processor', '1 TB SSD & 32 GB RAM', 'Tunn design & effektiv kylning', 10990, 8490);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (30, '17,3" laptop med Intel processor & 512 GB SSD', 'Acer Aspire 3 - A317-33-C1VR', -5, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-17-18-tum/acer-aspire-3-a317-33-c1vr(1031946)_634288_8_Normal_Large.jpg', 'IntelÂ® CeleronÂ® N4500 processor', '512 GB SSD & 8 GB RAM', 'Numeriskt tangentbord', 6499, 5690);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (31, '15,6'' laptop med AMD Ryzen 7 processor & 512 GB SSD', 'HP Pavilion 15-eh3004no', -7, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/hp-hp-pavilion-15-eh3004no(1030242)_612924_7_Normal_Large.jpg', 'AMD Ryzen 7 7730U processor', '512 GB SSD & 16 GB DDR4 RAM', '15,6" Full HD-skÃ¤rm (1920 x 1080)', 7990, 6990);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (32, 'Smidig 14" laptop med Intel processor & 512 GB SSD', 'Acer Aspire 3 (NX.A7SED.00R)', -1, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/acer-aspire-3-nx-a7sed-00r(1032811)_635873_3_Normal_Large.jpg', 'IntelÂ® CeleronÂ® N4500 processor', '512 GB SSD & 8 GB RAM', 'Slimmad design', NULL, 5799);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (33, '14" Full HD-laptop med Ryzenâ„¢ 5, Wi-Fi 6 & Windows 11', 'Acer Swift 3 (NX.AB1ED.00E)', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/acer-swift-3-nx-ab1ed-00e(1024712)_505552_1_Normal_Large.jpg', 'AMD Ryzenâ„¢ 5 5500U-processor', '512 GB SSD & 16 GB DDR4-RAM', 'Upp till 11.5 timmar batteritid', 6990, 6490);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (34, 'Kraftfull 14" laptop med i7 processor & 32 GB DDR5 RAM', 'Acer Aspire 5 14 - A514-56M-75KV', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/acer-aspire-5-14-a514-56m-75kv(1030919)_622664_1_Normal_Large.jpg', 'IntelÂ® Coreâ„¢ i7-1355U processor', '1 TB SSD & 32 GB DDR5 RAM', 'Full HD-webbkamera', 10990, 9990);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (35, '14" laptop med pekskÃ¤rm & 512 GB SSD-lagring', 'Acer Aspire 3 Spin 14 - A3SP14-31PT-378A', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/acer-aspire-3-spin-14-a3sp14-31pt-378a(1030927)_631759_9_Normal_Large.jpg', 'IntelÂ® Coreâ„¢ i3 N305 processor', '512 GB SSD & 8 GB DDR5 RAM', '360Â° gÃ¥ngjÃ¤rn', 6990, 5990);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (36, '14" laptop med AMD Ryzen 5 processor & 8 GB RAM', 'HP HP Laptop 14-em0924no', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/hp-hp-laptop-14-em0924no(1033705)_652502_1_Normal_Large.jpg', 'AMD Ryzen 5 7520U processor', '512 GB SSD & 8 GB RAM', '14" HD-skÃ¤rm (1366 x 768)', NULL, 5790);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (37, '14" laptop med AMD Ryzen 5 processor & 16 GB RAM', 'HP Laptop 14-em0926no', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/hp-hp-laptop-14-em0926no(1033709)_652223_1_Normal_Large.jpg', 'AMD Ryzen 5 7520U processor', '512 GB SSD & 16 GB RAM', '14" FHD IPS-skÃ¤rm (1920 x 1080)', NULL, 8090);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (38, '14" Chromebook Plus med AMD Ryzen-processor', 'Acer Chromebook CB514-3H-R4FL', -1, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/acer-chromebook-cb514-3h-r4fl(1030922)_618912_1_Normal_Large.jpg', 'AMD Ryzen 3 7320C processor', '128 GB SSD & 8 GB DDR5 RAM', 'Upp till 12 timmars batteritid', NULL, 6990);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (39, '15,6" Chromebook Plus med Intel Core i5-processor', 'Acer Chromebook Plus 515 15,6" FHD', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/acer-iris-xe-graphics-core-i5-1235u-8-gb-ram-256-gb-ssd-google-chrome-os(1032730)_624623_5_Normal_Large.jpg', 'Intel Core i5-1235U processor', '256 GB SSD & 8 GB DDR5 RAM', 'Upp till 10 timmars batteritid', NULL, 8490);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (40, '15,6" laptop med AMD Ryzenâ„¢ 5 Processor & Windows 11', 'HP Pavilion 15-eh3015no', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/hp-hp-pavilion-15-eh3015no(1032893)_639394_1_Normal_Large.jpg', 'AMD Ryzenâ„¢ 5 7530U Processor', '512 GB SSD & 16 GB DDR4-RAM', '15,6" Full HD-skÃ¤rm (1920 x 1080)', 8290, 6990);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (41, '15,6" laptop med AMD Ryzen 5 processor & 512 GB SSD', 'Lenovo IdeaPad 1', -5, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/lenovo-ideapad-1(1031215)_616019_7_Normal_Large.jpg', 'AMD Ryzenâ„¢ 5 5500U processor', '512 GB SSD & 8 GB RAM', 'HD-kamera med Privacy Shutter', NULL, 6490);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (42, '14" laptop med 12:e Gen. Intel Core i5 & 16 GB DDR5 RAM', 'Lenovo IdeaPad Slim 3', -2, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/lenovo-ideapad-slim-3(1031225)_622787_1_Normal_Large.jpg', 'IntelÂ® Coreâ„¢ i5-12450H processor', '512 GB SSD & 16 GB DDR5 RAM', 'Full HD-webbkamera med skydd', 7990, 6490);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (43, '15,6" laptop med snabb i5-processor & 1 TB SSD-lagring', 'MSI Modern 15 B12MO-864NEU', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/msi-modern-15-b12mo-864neu(1033170)_661696_4_Normal_Large.jpg', 'IntelÂ® Coreâ„¢ i5-1235U processor', '1 TB SSD & 16 GB RAM', 'Wi-Fi 6E & 1,5 mm tangenthÃ¶jd', NULL, 8899);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (44, 'LÃ¤tt & smidig 14" laptop med en snabb i5-processor', 'MSI Modern 14 C12MO-1087NEU', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/msi-modern-14-c12mo-1087neu(1033172)_659753_1_Normal_Large.jpg', 'Intel Core i5-1235U processor', '512 GB SSD & 8 GB RAM', 'VÃ¤ger endast 1,4 kg', NULL, 7790);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (45, '15,6" laptop med 12:e Gen. Intel Core i5 & 16 GB DDR5', 'Lenovo IdeaPad Slim 3', -3, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/lenovo-ideapad-slim-3(1031213)_622852_1_Normal_Large.jpg', 'IntelÂ® Coreâ„¢ i5-12450H processor', '512 GB SSD & 16 GB DDR5 RAM', 'Full HD-webbkamera med skydd', NULL, 7999);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (46, '14'' laptop med AMD Ryzen 7 processor & 512 GB SSD', 'Lenovo IdeaPad Flex 5', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/lenovo-ideapad-flex-5(1031226)_629489_4_Normal_Large.jpg', 'AMD Ryzen 7 7730U processor', '512 GB SSD & 16 GB DDR4 RAM', '14" WUXGA-skÃ¤rm med IPS-panel', 10499, 8990);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (47, '14" laptop med Full HD-pekskÃ¤rm & AMD Ryzen 7', 'Lenovo Flex 5 (82HU012EMX)', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/lenovo-flex-5-82hu012emx(1030943)_600115_8_Normal_Large.jpg', 'AMD Ryzenâ„¢ 7 5700U processor', '512 GB SSD & 16 GB RAM', '360-graders gÃ¥ngjÃ¤rn', 8799, 7990);

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength, strikeThrough, price) VALUES 
    (48, '16" laptop med IntelÂ® Coreâ„¢ i5-processor & 512 GB SSD', 'Medion  AKOYA E16423 (MD62558)', -3, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/medion-akoya-e16423-md62558(1031733)_611538_1_Normal_Large.jpg', 'IntelÂ® Coreâ„¢ i5-1155G7 processor', '512 GB SSD & 8 GB RAM', 'WiFi 5 och Bluetooth 5.0', NULL, 5990);
    

INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(49, 'MacBook Air 13"³. Tunn. Lätt. Kraften är upphöjd till M3.', 'Apple 13-inch MacBook Air: Apple M3 chip with 8-core CPU and 8-core GPU, 8GB, 256GB SSD - Midnight', -1, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/apple-13-inch-macbook-air-apple-m3-chip-with-8-core-cpu-and-8-core-gpu-8gb-256gb-ssd-midnight(1033610)_642329_3_Normal_Large.jpg', 'M3-chip med 8-kärnig processor', '256 GB SSD + 8 GB RAM', '13-tums Liquid Retina-skärm',NULL, 15690);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(50, 'MacBook Pro. Världens mest avancerade bärbara Mac.', 'Apple 14-inch MacBook Pro: Apple M3 Pro chip with 11"‘core CPU and 14"‘core GPU, 512GB SSD - Space Black', -3, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/apple-14-inch-macbook-pro-apple-m3-pro-chip-with-11core-cpu-and-14core-gpu-512gb-ssd-space-black(1032414)_616925_1_Normal_Large.jpg', 'M3-chip med 11-kärnig processor', '512 GB SSD + 18 GB RAM', '14"‘kärnig grafik',NULL, 26990);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(51, 'MacBook Air 13"³. Tunn. Lätt. Kraften är upphöjd till M3.', 'Apple 13-inch MacBook Air: Apple M3 chip with 8-core CPU and 10-core GPU, 16GB, 512GB SSD - Midnight', -1, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/apple-13-inch-macbook-air-apple-m3-chip-with-8-core-cpu-and-10-core-gpu-16gb-512gb-ssd-midnight(1033623)_642491_3_Normal_Large.jpg', 'M3-chip med 8-kärnig processor', '512 GB SSD + 16 GB RAM', '13-tums Liquid Retina-skärm',NULL, 18495);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(52, 'MacBook Pro 14"³. Superladdad med M3.', 'Apple 14-inch MacBook Pro: Apple M3 chip with 8"‘core CPU and 10"‘core GPU, 512GB SSD - Space Grey', -2, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/apple-14-inch-macbook-pro-apple-m3-chip-with-8core-cpu-and-10core-gpu-512gb-ssd-space-grey(1032383)_616811_1_Normal_Large.jpg', 'M3-chip med 8-kärnig processor', '512 GB SSD + 8 GB RAM', '10-kärnig grafik',NULL, 20990);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(53, 'MacBook Air. Superladdad med M2.', 'Apple MacBook Air 13" Midnight/M2 8C CPU   8C GPU/16GB RAM/512GB SSD/30W Power Adapter/Swedish Keyboard', -1, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/apple-macbook-air-13-midnightm2-8c-cpu-8c-gpu16gb-ram512gb-ssd30w-power-adapterswedish-keyboard(1031768)_613220_2_Normal_Large.jpg', 'Apple M2-chip med åttakärnig processor', '16 GB RAM + 512 GB SSD', '16-kärnig Neural Engine',NULL, 17490);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(54, 'MacBook Pro 13 tum. Superladdad med M2.', 'Apple Macbook Pro 13 MBP 13.3 SL/8C CPU/10C GPU/24GB/1TB-KSW', -1, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/apple-macbook-pro-13-mbp-13-3-sl8c-cpu10c-gpu24gb1tb-ksw(1032610)_624124_9_Normal_Large.jpg', 'M2-chip med åttakärnig processor', '24 GB RAM + 1 TB SSD', 'Tiokärnig grafikprocessor',NULL, 23990);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(55, 'MacBook Air 15"³. Oväntat stor. Ofattbart tunn.', 'Apple 15-inch MacBook Air: Apple M2 chip with 8-core CPU and 10-core GPU, 512GB - Silver', -1, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/apple-15-inch-macbook-air-apple-m2-chip-with-8-core-cpu-and-10-core-gpu-512gb-silver(1030299)_585772_1_Normal_Large.jpg', 'M2-chip för otrolig prestanda', '8 GB RAM + 512 GB SSD', '16-kärnig Neural Engine',NULL, 17790);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(56, 'MacBook Air 15"³. Oväntat stor. Ofattbart tunn.', 'Apple 15-inch MacBook Air: Apple M2 chip with 8-core CPU and 10-core GPU, 512GB - Starlight', -1, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/apple-15-inch-macbook-air-apple-m2-chip-with-8-core-cpu-and-10-core-gpu-512gb-starlight(1030301)_585807_1_Normal_Large.jpg', 'M2-chip för otrolig prestanda', '8 GB RAM + 512 GB SSD', '16-kärnig Neural Engine',NULL, 17790);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(57, 'MacBook Air. Superladdad med M2.', 'Apple 13-inch MacBook Air: Apple M2 chip with 8-core CPU and 10-core GPU, 512GB - Midnight', -14, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/apple-13-inch-macbook-air-apple-m2-chip-with-8-core-cpu-and-10-core-gpu-512gb-midnight(1025283)_511952_10_Normal_Large.jpg', 'Apple M2-chip med åttakärnig processor', '8 GB RAM + 512 GB SSD', '16-kärnig Neural Engine',NULL, 14790);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(58, 'MacBook Pro 14"³. Superladdad med M3.', 'Apple 14-inch MacBook Pro: Apple M3 chip with 8"‘core CPU and 10"‘core GPU, 512GB SSD - Silver', -2, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/apple-14-inch-macbook-pro-apple-m3-chip-with-8core-cpu-and-10core-gpu-512gb-ssd-silver(1032412)_616905_1_Normal_Large.jpg', 'M3-chip med 8-kärnig processor', '512 GB SSD + 8 GB RAM', '10-kärnig grafik',NULL, 20990);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(59, 'MacBook Pro 14"³. Superladdad med M3.', 'Apple 14-inch MacBook Pro: Apple M3 chip with 8-core CPU and 10-core GPU, 16GB, 1TB SSD - Space Grey', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/apple-14-inch-macbook-pro-apple-m3-chip-with-8core-cpu-and-10core-gpu-16gb-1tb-ssd-space-grey(1033602)_649900_1_Normal_Large.jpg', 'M3-chip med 8-kärnig processor', '1 TB SSD + 16 GB RAM', '10-kärnig grafik',NULL, 28990);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(60, 'MacBook Air 15"³. Tunn. Lätt. Kraften är upphöjd till M3.', 'Apple 15-inch MacBook Air: Apple M3 chip with 8-core CPU and 10-core GPU, 16GB, 512GB SSD - Midnight', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/apple-15-inch-macbook-air-apple-m3-chip-with-8-core-cpu-and-10-core-gpu-16gb-512gb-ssd-midnight(1033603)_642343_2_Normal_Large.jpg', 'M3-chip med med 8-kärnig processor', '512 GB SSD + 16 GB RAM', '15-tums Liquid Retina-skärm',NULL, 23590);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(61, 'MacBook Air 13"³. Tunn. Lätt. Kraften är upphöjd till M3.', 'Apple 13-inch MacBook Air: Apple M3 chip with 8-core CPU and 8-core GPU, 8GB, 256GB SSD - Space Grey', -1, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/apple-13-inch-macbook-air-apple-m3-chip-with-8-core-cpu-and-8-core-gpu-8gb-256gb-ssd-space-grey(1033604)_642311_3_Normal_Large.jpg', 'M3-chip med 8-kärnig processor', '256 GB SSD + 8 GB RAM', '13-tums Liquid Retina-skärm',NULL, 15690);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(62, 'MacBook Air 13"³. Tunn. Lätt. Kraften är upphöjd till M3.', 'Apple 13-inch MacBook Air: Apple M3 chip with 8-core CPU and 8-core GPU, 8GB, 256GB SSD - Silver', -1, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/apple-13-inch-macbook-air-apple-m3-chip-with-8-core-cpu-and-8-core-gpu-8gb-256gb-ssd-silver(1033606)_642392_3_Normal_Large.jpg', 'M3-chip med 8-kärnig processor', '256 GB SSD + 8 GB RAM', '13-tums Liquid Retina-skärm',NULL, 15690);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(63, 'MacBook Air 15"³. Tunn. Lätt. Kraften är upphöjd till M3.', 'Apple 15-inch MacBook Air: Apple M3 chip with 8-core CPU and 10-core GPU, 8GB, 256GB SSD - Midnight', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/apple-15-inch-macbook-air-apple-m3-chip-with-8-core-cpu-and-10-core-gpu-8gb-256gb-ssd-midnight(1033618)_642412_2_Normal_Large.jpg', 'M3-chip med med 8-kärnig processor', '256 GB SSD + 8 GB RAM', '15-tums Liquid Retina-skärm',NULL, 17990);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(64, 'MacBook Air. Superladdad med M2.', 'Apple 13-inch MacBook Air: Apple M2 chip with 8-core CPU and 10-core GPU, 512GB - Silver', -14, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/apple-13-inch-macbook-air-apple-m2-chip-with-8-core-cpu-and-10-core-gpu-512gb-silver(1025279)_511932_2_Normal_Large.jpg', 'Apple M2-chip med åttakärnig processor', '8 GB RAM + 512 GB SSD', '16-kärnig Neural Engine',NULL, 14790);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(65, 'MacBook Air 15"³. Tunn. Lätt. Kraften är upphöjd till M3.', 'Apple 15-inch MacBook Air: Apple M3 chip with 8-core CPU and 10-core GPU, 8GB, 256GB SSD - Starlight', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/apple-15-inch-macbook-air-apple-m3-chip-with-8-core-cpu-and-10-core-gpu-8gb-256gb-ssd-starlight(1033616)_642439_2_Normal_Large.jpg', 'M3-chip med med 8-kärnig processor', '256 GB SSD + 8 GB RAM', '15-tums Liquid Retina-skärm',NULL, 17990);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(66, 'MacBook Air 13"³. Tunn. Lätt. Kraften är upphöjd till M3.', 'Apple 13-inch MacBook Air: Apple M3 chip with 8-core CPU and 10-core GPU, 16GB, 512GB SSD - Space Grey', -1, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/apple-13-inch-macbook-air-apple-m3-chip-with-8-core-cpu-and-10-core-gpu-16gb-512gb-ssd-space-grey(1033620)_642448_3_Normal_Large.jpg', 'M3-chip med 8-kärnig processor', '512 GB SSD + 16 GB RAM', '13-tums Liquid Retina-skärm',NULL, 18495);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(67, 'MacBook Pro 14"³. Superladdad med M3.', 'Apple 14-inch MacBook Pro: Apple M3 chip with 8"‘core CPU and 10"‘core GPU, 1TB SSD - Space Grey', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/apple-14-inch-macbook-pro-apple-m3-chip-with-8core-cpu-and-10core-gpu-1tb-ssd-space-grey(1032384)_616970_1_Normal_Large.jpg', 'M3-chip med 8-kärnig processor', '1 TB SSD + 8 GB RAM', '10-kärnig grafik',NULL, 22990);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(68, 'MacBook Pro. Världens mest avancerade bärbara Mac.', 'Apple 14-inch MacBook Pro: Apple M3 Pro chip with 11"‘core CPU and 14"‘core GPU, 512GB SSD - Silver', -3, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/apple-14-inch-macbook-pro-apple-m3-pro-chip-with-11core-cpu-and-14core-gpu-512gb-ssd-silver(1032417)_617038_1_Normal_Large.jpg', 'M3-chip med 11-kärnig processor', '512 GB SSD + 18 GB RAM', '14"‘kärnig grafik',NULL, 26990);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(69, 'MacBook Air. Superladdad med M2.', 'Apple 13-inch MacBook Air: Apple M2 chip with 8-core CPU and 10-core GPU, 512GB - Space Grey', -14, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/apple-13-inch-macbook-air-apple-m2-chip-with-8-core-cpu-and-10-core-gpu-512gb-space-grey(1025277)_511916_2_Normal_Large.jpg', 'Apple M2-chip med åttakärnig processor', '8 GB RAM + 512 GB SSD', '16-kärnig Neural Engine',NULL, 14790);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(70, 'MacBook Air 13"³. Tunn. Lätt. Kraften är upphöjd till M3.', 'Apple 13-inch MacBook Air: Apple M3 chip with 8-core CPU and 10-core GPU, 8GB, 512GB SSD - Space Grey', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/apple-(1033605)_642264_2_Normal_Large.jpg', 'M3-chip med 8-kärnig processor', '512 GB SSD + 8 GB RAM', '13-tums Liquid Retina-skärm',NULL, 16290);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(71, 'MacBook Pro 14"³. Superladdad med M3.', 'Apple 14-inch MacBook Pro: Apple M3 chip with 8"‘core CPU and 10"‘core GPU, 1TB SSD - Silver', 0, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-12-14-tum/apple-14-inch-macbook-pro-apple-m3-chip-with-8core-cpu-and-10core-gpu-1tb-ssd-silver(1032420)_617002_1_Normal_Large.jpg', 'M3-chip med 8-kärnig processor', '1 TB SSD + 8 GB RAM', '10-kärnig grafik',NULL, 22990);
INSERT INTO products (id, title, subTitle, rating, imgSrc, listProcessor, listMemory, listStrength,strikeThrough, price) VALUES
(72, 'MacBook Air 13"³. Tunn. Lätt. Kraften är upphöjd till M3.', 'Apple 13-inch MacBook Air: Apple M3 chip with 8-core CPU and 8-core GPU, 8GB, 256GB SSD - Starlight', -1, 'https://www.netonnet.se/GetFile/ProductImagePrimary/dator-surfplatta/laptop/laptop-15-16-tum/apple-13-inch-macbook-air-apple-m3-chip-with-8-core-cpu-and-8-core-gpu-8gb-256gb-ssd-starlight(1033608)_642403_3_Normal_Large.jpg', 'M3-chip med 8-kärnig processor', '256 GB SSD + 8 GB RAM', '13-tums Liquid Retina-skärm',NULL, 15690);
